COLUMN EMP_ID FORMAT 9999;
COLUMN FNAME FORMAT A10;
COLUMN LNAME FORMAT A10;
COLUMN DEPT_ID FORMAT 9999;
COLUMN MANAGER_EMP_ID FORMAT 9999;
COLUMN SALARY FORMAT $999,999;
COLUMN HIRE_DATE FORMAT A10;
COLUMN JOB_ID FORMAT 9999;

SELECT EMP_ID,FNAME,LNAME,DEPT_ID,MANAGER_EMP_ID,SALARY,HIRE_DATE,JOB_ID FROM EMPLOYEE;

COLUMN JEFE A15;

SELECT FNAME,LNAME,EMP_ID,NVL(TO_CHAR(MANAGER_EMP_ID),'JEFE DE JEFES')JEFE
FROM EMPLOYEE
START WITH MANAGER_EMP_ID IS NULL
CONNECT BY PRIOR EMP_ID = MANAGER_EMP_ID;

SELECT E_TOP.LNAME,E_2.LNAME,E_3.LNAME,E_4.LNAME FROM EMPLOYEE E_TOP LEFT OUTER JOIN EMPLOYEE E_2
ON E_TOP.EMP_ID = E_2.MANAGER_EMP_ID
LEFT OUTER JOIN EMPLOYEE E_3 ON E_2.EMP_ID = E_3.MANAGER_EMP_ID
LEFT OUTER JOIN EMPLOYEE E_4 ON E_3.EMP_ID = E_4.MANAGER_EMP_ID
WHERE E_TOP.MANAGER_EMP_ID IS NULL;

SELECT E_TOP.EMP_ID,E_TOP.LNAME,E_2.EMP_ID,E_2.LNAME,E_3.EMP_ID,E_3.LNAME,E_4.EMP_ID,E_4.LNAME FROM EMPLOYEE E_TOP LEFT OUTER JOIN EMPLOYEE E_2
ON E_TOP.EMP_ID = E_2.MANAGER_EMP_ID
LEFT OUTER JOIN EMPLOYEE E_3 ON E_2.EMP_ID = E_3.MANAGER_EMP_ID
LEFT OUTER JOIN EMPLOYEE E_4 ON E_3.EMP_ID = E_4.MANAGER_EMP_ID
WHERE E_TOP.MANAGER_EMP_ID IS NULL;

SELECT LNAME,EMP_ID,MANAGER_EMP_ID
FROM EMPLOYEE
START WITH LNAME= 'JONES'
CONNECT BY MANAGER_EMP_ID = PRIOR EMP_ID;

SELECT LNAME,HIRE_DATE,EMP_ID,MANAGER_EMP_ID
FROM EMPLOYEE
START WITH HIRE_DATE = (SELECT MIN(HIRE_DATE) FROM EMPLOYEE)
CONNECT BY MANAGER_EMP_ID = PRIOR EMP_ID;

SELECT LEVEL,LNAME,EMP_ID,MANAGER_EMP_ID
FROM EMPLOYEE
START WITH MANAGER_EMP_ID IS NULL
CONNECT BY MANAGER_EMP_ID = PRIOR EMP_ID;

SELECT MAX(LEVEL)NIVEL_MAX
FROM EMPLOYEE
START WITH MANAGER_EMP_ID IS NULL
CONNECT BY PRIOR EMP_ID = MANAGER_EMP_ID;

SELECT LEVEL NIVEL,COUNT(EMP_ID) EMP_X_NIVEL
FROM EMPLOYEE
START WITH MANAGER_EMP_ID IS NULL
CONNECT BY PRIOR EMP_ID = MANAGER_EMP_ID;

COLUMN NIVEL FORMAT 9999
COLUMN EMPLEADO FORMAT A20
COLUMN GERENTE FORMAT A14
SELECT LEVEL NIVEL, LPAD(' ',4*(LEVEL-1)) || LNAME "EMPLEADO", EMP_ID, NVL(TO_CHAR(MANAGER_EMP_ID),'JEFE DE JEFES')GERENTE,SALARY
FROM EMPLOYEE
WHERE SALARY > 2000
START WITH MANAGER_EMP_ID IS NULL
CONNECT BY MANAGER_EMP_ID = PRIOR EMP_ID;

SELECT LEVEL,LPAD(' ',5*(LEVEL-1)) || LNAME "EMPLEADO", EMP_ID, NVL(TO_CHAR(MANAGER_EMP_ID),'JEFE DE JEFES')GERENTE,SALARY
FROM EMPLOYEE
CONNECT BY MANAGER_EMP_ID = PRIOR EMP_ID;

SELECT EMP_ID,LNAME,DEPT_ID,MANAGER_EMP_ID,SALARY,HIRE_DATE
FROM EMPLOYEE
WHERE LNAME = 'SMITH'
START WITH LNAME = 'JONES'
CONNECT BY MANAGER_EMP_ID = PRIOR EMP_ID;

SELECT EMP_ID,LNAME,DEPT_ID,NVL(TO_CHAR(MANAGER_EMP_ID),'JEFE DE JEFES')GERENTE,SALARY,HIRE_DATE
FROM EMPLOYEE
WHERE LEVEL  <= 2
START WITH MANAGER_EMP_ID IS NULL
CONNECT BY MANAGER_EMP_ID = PRIOR EMP_ID;

ALTER SESSION SET NLS_DATE_LANGUAGE = 'ENGLISH';

DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;

CREATE TABLE EMPLOYEE(
  EMP_ID NUMBER(5) NOT NULL,
  FNAME VARCHAR2(20),
  LNAME VARCHAR2(20),
  DEPT_ID NUMBER(5) NOT NULL,
  MANAGER_EMP_ID NUMBER(5)M
  SALARY NUMBER(5),
  HIRE_DATE DATE,
  JOB_ID NUMBER(3),
  CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMP_ID)
);

INSERT INTO EMPLOYEE
(EMP_ID,FNAME,LNAME,DEPT_ID,MANAGER_EMP_ID,SALARY,HIRE_DATE,JOB_ID)
SELECT E.EMP_ID,E.FNAME,E.LNAME,E.DEPT_ID,E.MANAGER_EMP_ID,E.SALARY,E.HIRE_DATE,E.JOB_ID
FROM
(
  SELECT 7369 EMP_ID,'JHON' FNAME, 'SMITH' LNAME, 20 DEPT_ID, 7902 MANAGER_EMP_ID, 800 SALARY, '17-DEC-80' HIRE_DATE, 667 JOB_ID FROM DUAL UNION ALL
  SELECT 7499 EMP_ID,'KEVIN' FNAME, 'ALLEN' LNAME, 30 DEPT_ID, 7698 MANAGER_EMP_ID, 800 SALARY, '20-FEB-81' HIRE_DATE, 670 JOB_ID FROM DUAL UNION ALL
  SELECT 7521 EMP_ID,'CYNTHIA' FNAME, 'WARD' LNAME, 30 DEPT_ID, 7698 MANAGER_EMP_ID, 800 SALARY, '22-FEB-81' HIRE_DATE, NULL JOB_ID FROM DUAL UNION ALL
  SELECT 7566 EMP_ID,'TERRY' FNAME, 'JONES' LNAME, 20 DEPT_ID, 7839 MANAGER_EMP_ID, 800 SALARY, '02-APR-81' HIRE_DATE, 671 JOB_ID FROM DUAL UNION ALL
  SELECT 7654 EMP_ID,'KENNETH' FNAME, 'MARTIN' LNAME, 30 DEPT_ID, 7698 MANAGER_EMP_ID, 800 SALARY, '28-SEP-81' HIRE_DATE, 670 JOB_ID FROM DUAL UNION ALL
  SELECT 7698 EMP_ID,'MARION' FNAME, 'BLAKE' LNAME, 30 DEPT_ID, 7839 MANAGER_EMP_ID, 800 SALARY, '01-MAY-80' HIRE_DATE, 671 JOB_ID FROM DUAL UNION ALL
  SELECT 7782 EMP_ID,'CAROL' FNAME, 'CLARK' LNAME, 10 DEPT_ID, 7839 MANAGER_EMP_ID, 800 SALARY, '09-JUN-81' HIRE_DATE, 671 JOB_ID FROM DUAL UNION ALL
  SELECT 7788 EMP_ID,'DONALD' FNAME, 'SCOTT' LNAME, 20 DEPT_ID, 7566 MANAGER_EMP_ID, 800 SALARY, '19-APR-87' HIRE_DATE, 669 JOB_ID FROM DUAL UNION ALL
  SELECT 7839 EMP_ID,'FRANCIS' FNAME, 'KING' LNAME, 10 DEPT_ID, NULL MANAGER_EMP_ID, 800 SALARY, '17-NOV-81' HIRE_DATE, 672 JOB_ID FROM DUAL UNION ALL
  SELECT 7844 EMP_ID,'MARY' FNAME, 'TURNER' LNAME, 30 DEPT_ID, 7698 MANAGER_EMP_ID, 800 SALARY, '08-SEP-81' HIRE_DATE, 670 JOB_ID FROM DUAL UNION ALL
  SELECT 7876 EMP_ID,'DIANE' FNAME, 'ADAMS' LNAME, 20 DEPT_ID, 7788 MANAGER_EMP_ID, 800 SALARY, '23-MAY-87' HIRE_DATE, NULL JOB_ID FROM DUAL UNION ALL
  SELECT 7900 EMP_ID,'FRED' FNAME, 'JAMES' LNAME, 30 DEPT_ID, 7698 MANAGER_EMP_ID, 800 SALARY, '03-DEC-81' HIRE_DATE, 667 JOB_ID FROM DUAL UNION ALL
  SELECT 7902 EMP_ID,'JENNIFER' FNAME, 'FORD' LNAME, 20 DEPT_ID, 7566 MANAGER_EMP_ID, 800 SALARY, '03-DEC-81' HIRE_DATE, 669 JOB_ID FROM DUAL UNION ALL
  SELECT 7934 EMP_ID,'BARBARA' FNAME, 'MILLER' LNAME, 10 DEPT_ID, 7782 MANAGER_EMP_ID, 800 SALARY, '23-JAN-82' HIRE_DATE, 667 JOB_ID FROM DUAL
)E;

COMMIT;
