CREATE TABLE TOY(
  TOY_ID NUMBER(10),
  DESCRIPTION VARCHAR2(15) NOT NULL
  LAST_PURCHASE_DATE DATE,
  REMAINING_QUANTITY NUMBER(6)
);

CREATE TABLE TAB1(
  COL1 NUMBER(10),
  COL2 NUMBER(4) CONSTRAINT TAB1_COL2_NN NOT NULL,
  COL3 VARCHAR2(5),
  COL4 DATE DEFAULT SYSDATE,
  COL5 VARCHAR2(20),
  COL6 NUMBER,
  CONSTRAINT TAB1_PK PRIMARY KEY(COL1),
  CONSTRAINT TAB1_ZIPCODE_FK FOREIGN KEY(COL3) REFERENCES ZIPCODE(ZIP),
  CONSTRAINT TAB1_COL5_COL6_UK UNIQUE(COL5,COL6),
  CONSTRAINT TAB1_COL6_CK CHECK(COL6 < 100),
  CONSTRAINT TAB1_COL2_COL6_CK CHECK(COL2>100 AND COL6>20)
);

CREATE OR REPLACE TRIGGER STUDENT_TRG_BUR BEFORE UPDATE ON STUDENT FOR EACH ROW
BEGIN
  :NEW.MODIFIED_DATE:=SYSDATE;
END;

CREATE TABLE JAN_03_ENROLLMENT AS
SELECT *
  FROM ENROLLMENT
  WHERE ENROLL_DATE >=
    TO_DATE('01/01/2003','MM/DD/YYYY')
  AND ENROLL_DATE <
    TO_DATE('02/01/2003','MM/DD/YYYY');

DESC JAN_03_ENROLLMENT;

SELECT STUDENT_ID,SECTION_ID,ENROLL_DATE FROM JAN_03_ENROLLMENT;

DROP TABLE ZIPCODE CASCADE CONSTRAINTS;

DROP TABLE JAN_03;

SELECT OBJECT_NAME,ORIGINAL_NAME,TYPE FROM USER_RECYCLEBIN;

SHOW RECYCLEBIN;

PURGE RECYCLEBIN;

CREATE TABLE SCHOOL_PROGRAM AS
SELECT LAST_NAME||', '||FIRST_NAME FROM STUDENT UNION
SELECT LAST_NAME||', '||FIRST_NAME FROM INSTRUCTOR;

SELECT * FROM SCHOOL_PROGRAM; 
