--Esquema
--Calette Cornelio Javier

DROP TABLE EMPLEADO;
DROP TABLE SALARIO;
DROP TABLE OBLIGACION;
SET serveroutput ON
SET LINESIZE 250;
COLUMN ID_EMP FORMAT 9999;
COLUMN NOMBRE FORMAT A30;
COLUMN RFC FORMAT A14;
COLUMN CURP FORMAT A18;
COLUMN DESCRIPCION FORMAT A15;
COLUMN CLAVE_EMPLEADO FORMAT A14;
COLUMN OBJECT_NAME FORMAT A20;
COLUMN STATUS FORMAT A8;
COLUMN TABLE_NAME FORMAT A12;
COLUMN TRIGGER_NAME FORMAT A20;

CREATE TABLE EMPLEADO
 (ID_EMP NUMBER(9,0),
  NOMBRE VARCHAR2(80),
  RFC VARCHAR2(30),
  CURP VARCHAR2(20),
  DESCRIPCION VARCHAR2(20),
  CLAVE_EMPLEADO VARCHAR2(17)
);

CREATE TABLE SALARIO
 (ID_SAL NUMBER(9,0),
  MONTO VARCHAR2(30),
  DIAS NUMBER(6,0),
  FORMULA VARCHAR2(20)
);

CREATE TABLE OBLIGACION
 (ID_OB NUMBER(9,0),
  TEXTO VARCHAR2(50)
);
