--POR ULTIMO SE DEBEN PROBAR LOS PROCEDIMIENTOS QUE SE DECLARADON ANTERIORMENTE
--CALETTE CORNELIO JAVIER

SELECT CURP FROM EMPLEADO;

BEGIN
GET_NAME_BY_MONTH('10');
END;
/

SELECT MONTO FROM SALARIO;

BEGIN
GET_CAPICUA;
END;
/

SELECT NOMBRE FROM EMPLEADO;

BEGIN
GET_COMPUESTOS;
END;
/

--Finalmente se agregan las restricciones correctas
ALTER TRIGGER VALIDA_DIAS DISABLE;
ALTER TRIGGER VALIDA_CURP DISABLE;
ALTER TRIGGER VALIDA_RFC DISABLE;
ALTER TRIGGER VALIDA_TEXTO DISABLE;
ALTER TRIGGER VALIDA_MONTO DISABLE;

ALTER TABLE EMPLEADO ADD CONSTRAINT CURP_CONS CHECK (REGEXP_LIKE(CURP,'^[A-Z][AEIOU][A-Z]{2}[0-9]{2}(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[HM](AS|BC|BS|CC|CS|CH|CL|CM|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[B-DF-HJ-NP-TV-Z]{3}[0-9A-Z][0-9]$'));
ALTER TABLE EMPLEADO ADD CONSTRAINT RFC_CONS CHECK (REGEXP_LIKE(RFC,'^[A-Z][AEIOU][A-Z]{2}[0-9]{2}(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[0-9A-Z]{3}$'));
ALTER TABLE EMPLEADO ADD CONSTRAINT CLAVE_CONS CHECK (REGEXP_LIKE(clave_empleado,'^[0-9]{4}[A-Z][AEIOU][A-Z][0-9a-fA-F]{5}$'));

ALTER TABLE SALARIO ADD CONSTRAINT Dias_CONS CHECK(dias < 15);
ALTER TABLE SALARIO ADD CONSTRAINT MONTO_CONS CHECK(REGEXP_LIKE(MONTO,'^\$\(?[0-9]{1,3}([\,][0-9]{3})*\.[0-9]{2}\)?$'));
ALTER TABLE SALARIO ADD CONSTRAINT Formula_CONS CHECK (REGEXP_LIKE(formula,'\(([^()]|(?R))*\)'));

ALTER TABLE OBLIGACION ADD CONSTRAINT Texto_CONS CHECK (NOT REGEXP_LIKE(texto,'(MV|NP|NB|mv|np|nb)'));
