DROP TABLE EMPLEADO;
DROP TABLE SALARIO;
DROP TABLE OBLIGACION;
SET serveroutput ON

CREATE TABLE Empleado
 (ID_EMP NUMBER(9,0),
  Nombre VARCHAR2(30),
  RFC VARCHAR2(30),
  CURP VARCHAR2(20),
  Descripcion VARCHAR2(20),
  clave_empleado VARCHAR2(17)
);

CREATE TABLE SALARIO
 (ID_SAL NUMBER(9,0),
  monto VARCHAR2(30),
  dias NUMBER(6,0),
  formula VARCHAR2(20)
);

CREATE TABLE OBLIGACION
 (ID_OB NUMBER(9,0),
  texto VARCHAR2(50)
);

-- TRIGGERS
CREATE OR REPLACE TRIGGER VALIDA_DIAS
BEFORE INSERT ON SALARIO FOR EACH ROW
DECLARE
BEGIN
    IF :NEW.DIAS > 15 THEN
      RAISE_APPLICATION_ERROR (-20001,'EL VALOR DEL CAMPO DIAS DEBE SER MENOR A 15');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER VALIDA_CURP
BEFORE INSERT ON EMPLEADO FOR EACH ROW
DECLARE
BEGIN
    IF NOT REGEXP_LIKE(:NEW.CURP,'^[A-Z][AEIOU][A-Z]{2}[0-9]{2}(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[HM](AS|BC|BS|CC|CS|CH|CL|CM|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[B-DF-HJ-NP-TV-Z]{3}[0-9A-Z][0-9]$') THEN
      RAISE_APPLICATION_ERROR (-20001,'CURP MAL REALIZADA');
    END IF;
END;
/

--Finalmente se agregan las restricciones correctas
ALTER TABLE EMPLEADO ADD CONSTRAINT CURP_CONS CHECK (REGEXP_LIKE(CURP,'^[A-Z][AEIOU][A-Z]{2}[0-9]{2}(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[HM](AS|BC|BS|CC|CS|CH|CL|CM|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[B-DF-HJ-NP-TV-Z]{3}[0-9A-Z][0-9]$'));
ALTER TABLE EMPLEADO ADD CONSTRAINT RFC_CONS CHECK (REGEXP_LIKE(RFC,'^[A-Z][AEIOU][A-Z]{2}[0-9]{2}(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[0-9A-Z]{3}$'));
ALTER TABLE EMPLEADO ADD CONSTRAINT CLAVE_CONS CHECK (REGEXP_LIKE(clave_empleado,'^[0-9]{4}[A-Z][AEIOU][A-Z][0-9a-fA-F]{5}$'));

ALTER TABLE SALARIO ADD CONSTRAINT Dias_CONS CHECK(dias < 15);
ALTER TABLE SALARIO ADD CONSTRAINT MONTO_CONS CHECK(REGEXP_LIKE(MONTO,'^\$\(?[0-9]{1,3}([\,][0-9]{3})*\.[0-9]{2}\)?$'));
ALTER TABLE SALARIO ADD CONSTRAINT Formula_CONS CHECK (REGEXP_LIKE(formula,'\(([^()]|(?R))*\)'));

ALTER TABLE OBLIGACION ADD CONSTRAINT Texto_CONS CHECK (NOT REGEXP_LIKE(texto,'(MV|NP|NB|mv|np|nb)'));



--INSERCION DE DATOS

INSERT INTO OBLIGACION VALUES (1,'Javier');
INSERT INTO OBLIGACION VALUES (2,'ENBIDIA');
INSERT INTO SALARIO VALUES (1,'$100,000.00',3,'((A)(B)');
INSERT INTO EMPLEADO VALUES (1,'Javier','CACJ961128H10','CACJ961128HMCLRV11','Descripcion','1995CACFFFF0');
--SELECT * FROM EMPLEADO WHERE REGEXP_LIKE(RFC,'^[A-Z][AEIOU][A-Z]{2}[0-9]{2}(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[0-9A-Z]{3}$')
--'^[A-Z][AEIOU][A-Z]{2}[0-9]{2}(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])[0-9A-Z]{3}$'--RFC
--SELECT * FROM SALARIO WHERE REGEXP_LIKE(MONTO,'^\$\(?[0-9]{1,3}([\,][0-9]{3})*\.[0-9]{2}\)?$');
