DECLARE
CURSOR CURSOS IS SELECT COURSE_NO,DESCRIPTION FROM COURSE;
CURSOR INSCRIPCIONES(CURSO COURSE.COURSE_NO%TYPE) IS SELECT SECTION_NO,COUNT(*) INSCRITOS FROM SECTION, ENROLLMENT WHERE SECTION.COURSE_NO = CURSO AND SECTION.SECTION_ID = ENROLLMENT.SECTION_ID GROUP BY SECTION_NO;
BEGIN
  FOR AUX IN CURSOS LOOP
  DBMS_OUTPUT.PUT_LINE(CHR(9)||'CURSO: '||AUX.DESCRIPTION);
    FOR AUX2 IN INSCRIPCIONES(AUX.COURSE_NO) LOOP
    DBMS_OUTPUT.PUT_LINE('SECTION: '||AUX2.SECTION_NO||' INSCRITOS: '||AUX2.INSCRITOS);
    END LOOP;
  END LOOP;
END;
/

DECLARE
CURSOR CURSOS IS SELECT DISTINCT COURSE_NO FROM SECTION WHERE SECTION.CAPACITY = (SELECT COUNT(SECTION_ID) FROM ENROLLMENT WHERE ENROLLMENT.SECTION_ID = SECTION.SECTION_ID);
CURSOR CURSOS_2 IS SELECT COURSE_NO FROM SECTION WHERE ROWNUM<=2 GROUP BY COURSE_NO;
INSTRUCTOR_AUX INSTRUCTOR.INSTRUCTOR_ID%TYPE;
ID_SECTION_1 SECTION.SECTION_ID%TYPE;
SECTION_NO_1 SECTION.SECTION_NO%TYPE := 1;
BEGIN
FOR C IN CURSOS LOOP
  IF CURSOS%NOTFOUND THEN
    SELECT INSTRUCTOR_ID INTO INSTRUCTOR_AUX FROM INSTRUCTOR WHERE EXISTS (SELECT NULL FROM SECTION WHERE SECTION.INSTRUCTOR_ID = INSTRUCTOR.INSTRUCTOR_ID GROUP BY INSTRUCTOR_ID HAVING COUNT(*) = (SELECT MIN(COUNT(*)) FROM SECTION WHERE INSTRUCTOR_ID IS NOT NULL GROUP BY INSTRUCTOR_ID)) AND ROWNUM = 1;
    FOR C2 IN CURSOS_2 LOOP
      SELECT MAX(SECTION_ID) + 1 INTO ID_SECTION_1 FROM SECTION;
      INSERT INTO SECTION (SECTION_ID, COURSE_NO, SECTION_NO, INSTRUCTOR_ID) VALUES (ID_SECTION_1, C2.COURSE_NO, SECTION_NO_1, INSTRUCTOR_AUX);
      COMMIT;
    END LOOP;
  ELSE
    DBMS_OUTPUT.PUT_LINE('CURSO LLENO: '||C.COURSE_NO);
  END IF;
END LOOP;
EXCEPTION
  WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE ('ERROR');
END;
/
