CREATE OR REPLACE PROCEDURE PROCESO_1 IS
  DIA CHAR(1);
  USUARIO VARCHAR2(30);
  AUX NUMBER;
  AUX2 NUMBER;
BEGIN
  SELECT SUBSTR(TO_CHAR(SYSDATE, 'DAY'), 0, 1) INTO DIA FROM DUAL;

  IF DIA = 'S' THEN DBMS_OUTPUT.PUT_LINE ('FIN DE SEMANA');
  ELSE
  DBMS_OUTPUT.PUT_LINE ('NO ES FIN DE SEMANA');
  END IF;

  DBMS_OUTPUT.PUT_LINE('HORA: '|| TO_CHAR(SYSDATE, 'HH:MI AM'));

  SELECT USER INTO USUARIO FROM DUAL;
  DBMS_OUTPUT.PUT_LINE ('USUARIO: '||USUARIO);

  SELECT NVL(COUNT(*), 0) INTO AUX FROM USER_OBJECTS WHERE STATUS = 'VALID' AND OBJECT_TYPE = 'PROCEDURE';
  DBMS_OUTPUT.PUT_LINE('PROCESOS VALIDOS: '||AUX);

  SELECT NVL(COUNT(*), 0) INTO AUX2 FROM USER_OBJECTS WHERE STATUS = 'INVALID'AND OBJECT_TYPE = 'PROCEDURE';
  DBMS_OUTPUT.PUT_LINE('PROCESOS INVALIDOS: '||AUX2);
END;
/

---Segunda Parte

CREATE OR REPLACE PROCEDURE PROCESO_2 (TABLE_NAME_IN IN VARCHAR2 ,ID_IN IN NUMBER ,FIRST_NAME_OUT OUT VARCHAR2 ,LAST_NAME_OUT OUT VARCHAR2 ,STREET_OUT OUT VARCHAR2 ,CITY_OUT OUT VARCHAR2 ,STATE_OUT OUT VARCHAR2 ,ZIP_OUT OUT VARCHAR2) IS

SQL_STMT VARCHAR2(200);

BEGIN

SQL_STMT := 'SELECT A.FIRST_NAME, A.LAST_NAME, A.STREET_ADDRESS'|| ' ,B.CITY, B.STATE, B.ZIP' || ' FROM '||TABLE_NAME_IN||' A, ZIPCODE B' || ' WHERE A.ZIP = B.ZIP' || ' AND '||TABLE_NAME_IN||'_ID = :1';

EXECUTE IMMEDIATE SQL_STMT

INTO FIRST_NAME_OUT, LAST_NAME_OUT, STREET_OUT, CITY_OUT, STATE_OUT, ZIP_OUT USING ID_IN;
END;
/

DECLARE
  V_TABLE_NAME VARCHAR2(20) := '&TABLA';
  V_ID NUMBER := &ID;
  V_FIRST_NAME VARCHAR2(25);
  V_LAST_NAME VARCHAR2(25);
  V_STREET VARCHAR2(50);
  V_CITY VARCHAR2(25);
  V_STATE VARCHAR2(2);
  V_ZIP VARCHAR2(5);
BEGIN
  PROCESO_2(V_TABLE_NAME, V_ID, V_FIRST_NAME, V_LAST_NAME, V_STREET, V_CITY, V_STATE, V_ZIP);
  DBMS_OUTPUT.PUT_LINE ('PRIMER NOMBRE: '||V_FIRST_NAME);
  DBMS_OUTPUT.PUT_LINE ('APELLIDO: '||V_LAST_NAME);
  DBMS_OUTPUT.PUT_LINE ('DIRECCION: '||V_STREET);
  DBMS_OUTPUT.PUT_LINE ('CUIDAD: '||V_CITY);
  DBMS_OUTPUT.PUT_LINE ('ESTADO: '||V_STATE);
  DBMS_OUTPUT.PUT_LINE ('ZIP: '||V_ZIP);
END;
/
